Updated my day39 work
ambigai-rajan/Qxf2_internship_22 pull request #51
Opened 2023-01-25 04:28 UTC by ambigai-rajan

2023-01-25 04:30 UTC, ambigai-rajan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Updating Day-39 work[Ambigai Rajan]](https://trello.com/c/4Z9TU5Ru/24-updating-day-39-workambigai-rajan)

2023-01-25 06:19 UTC, shivahari requested changes
Did you intentionally change previous day work?
`pythonanywhere` seems to have gone back to `Python anywhere`

2023-01-25 10:02 UTC, sathyanmadhavan approved these changes

2023-01-25 10:06 UTC, ambigai-rajan commented
> Did you intentionally change previous day work? `pythonanywhere` seems to have gone back to `Python anywhere`

No I didn't change that `pythonanywhere` to `python anywhere` when I create a pull request I have conflicts in `README.md` file when I tried to resolve the conflict I missed to note this change Now I changed it

2023-01-27 11:30 UTC, shivahari approved these changes

2023-01-27 11:48 UTC, merged